spring:
  datasource:
    url: jdbc:mysql://localhost:3306/StaffDatabase
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: none 
  sql:
    init:
      mode: always
